<?php
/**
 * Created by PhpStorm.
 * User: macbook
 * Date: 2019-01-27
 * Time: 17:34
 */
include_once ('Point.php');
class moveable extends Point
{
    public $xSpeed;
    public $ySpeed;
    public function __construct($x,$y,$xSpeed,$ySpeed)
    {
        parent::__construct($x,$y);
        $this->xSpeed=$xSpeed;
        $this->ySpeed=$ySpeed;
    }
    function setxSpeed($xSpeed)
    {
        $this->xSpeed=$xSpeed;
    }
    function setySpeed($ySpeed)
    {
        $this->ySpeed=$ySpeed;
    }
    function getxSpeed()
    {
        return $this->xSpeed;
    }
    function getySpeed()
    {
        return $this->ySpeed;
    }
    function setxSpeedySpeed($x,$y,$xSpeed,$ySpeed)
    {
        $this->x=$x;
        $this->y=$y;
        $this->xSpeed=$xSpeed;
        $this->ySpeed=$ySpeed;
    }
    function getxSpeedySpeed()
    {
        //parent::getxy();
        $arr[]=$this->x;
        $arr[]=$this->y;
        $arr[]=$this->xSpeed;
        $arr[]=$this->ySpeed;
        return json_encode($arr);
    }
    function __toString()
    {
        return 'MoveveaPoint:'.$this->getxSpeedySpeed(); // TODO: Change the autogenerated stub
    }

}
?>